"""Export the endpulse Click CLI as a machine-readable JSON catalogue.

Usage
-----
    python scripts/export_commands.py [--output PATH]

Writes `commands.json` at the repo root by default (or at `--output`).
The output is consumed by LLM-discoverability surfaces (llms.txt, docs)
so LLMs and search tools can enumerate the CLI without parsing `--help` text.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import click

from endpulse import __version__
from endpulse.cli import main as endpulse_main


_JSON_PRIMITIVES = (str, int, float, bool, type(None))


def _safe_default(value: Any) -> Any | None:
    """Return `value` if JSON-serializable, else None.

    Click uses internal sentinel objects for unspecified defaults
    (e.g. click.core._Unset) that are not JSON serializable.
    """
    if value is None or callable(value):
        return None
    if isinstance(value, _JSON_PRIMITIVES):
        return value
    if isinstance(value, (list, tuple)):
        return [v for v in value if isinstance(v, _JSON_PRIMITIVES)]
    return None


def _param_to_dict(param: click.Parameter) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "name": param.name,
        "param_type": param.param_type_name,
        "required": bool(param.required),
    }

    if isinstance(param, click.Option):
        entry["opts"] = list(param.opts)
        entry["secondary_opts"] = list(param.secondary_opts)
        entry["is_flag"] = bool(param.is_flag)
        entry["multiple"] = bool(param.multiple)
        default_value = _safe_default(param.default)
        if default_value is not None:
            entry["default"] = default_value
        if param.help:
            entry["help"] = param.help
        if isinstance(param.type, click.Choice):
            entry["choices"] = list(param.type.choices)
        else:
            entry["type"] = getattr(param.type, "name", str(param.type))
    elif isinstance(param, click.Argument):
        entry["nargs"] = param.nargs
        entry["type"] = getattr(param.type, "name", str(param.type))

    return entry


def _command_to_dict(cmd: click.Command, name: str) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "name": name,
        "help": (cmd.help or "").strip(),
        "short_help": (cmd.get_short_help_str() or "").strip(),
        "params": [_param_to_dict(p) for p in cmd.params],
    }
    if isinstance(cmd, click.Group):
        entry["subcommands"] = [
            _command_to_dict(sub, sub_name)
            for sub_name, sub in sorted(cmd.commands.items())
        ]
    return entry


def build_catalogue() -> dict[str, Any]:
    root: dict[str, Any] = {
        "name": "endpulse",
        "version": __version__,
        "description": "Async multi-endpoint HTTP health checker with assertions, SSL monitoring, and webhook alerts.",
        "source": "generated by scripts/export_commands.py",
        "commands": [_command_to_dict(endpulse_main, "endpulse")],
    }
    return root


def main() -> int:
    parser = argparse.ArgumentParser(description="Export endpulse CLI as JSON.")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "commands.json",
        help="Output path (default: <repo>/commands.json).",
    )
    args = parser.parse_args()

    catalogue = build_catalogue()
    args.output.write_text(
        json.dumps(catalogue, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {args.output} ({len(catalogue['commands'][0]['params'])} top-level params)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
